#!/usr/bin/env bash
# Script that displays information about subdomains

# Function to get subdomain info

domain=$1
subdomain=$2

get_info() {
  local sub=$1
  local output
  output=$(dig +short A ${sub}.${domain})
  if [ -n "$output" ]; then
    echo "The subdomain ${sub} is a A record and points to ${output}"
  fi
}

if [ -z "$domain" ]; then
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi

if [ -z "$subdomain" ]; then
  for sub in www lb-01 web-01 web-02; do
    get_info "$sub"
  done
else
  get_info "$subdomain"
fi
